name: wisely_diary
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.9
  flutter_signin_button: ^2.0.0
  flutter_secure_storage: ^9.2.2
  provider: ^6.0.0
  google_sign_in: ^6.2.1
  kakao_flutter_sdk_user: ^1.9.5
  table_calendar: ^3.0.9
  http: ^1.1.0
  path_provider: ^2.0.15
  path: ^1.8.3
  flutter_dotenv: ^5.0.2
  just_audio: ^0.9.34
  speech_to_text: ^6.6.0
  permission_handler: ^11.3.1
  http_parser: ^4.0.0
  image_picker: ^0.8.4+3
  cupertino_icons: ^1.0.6
  record: ^5.1.2
  android_alarm_manager_plus: ^3.0.4
  gotrue: any
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.2.1+2
  timezone: ^0.9.4
  device_info_plus: ^10.1.1
  path_provider_android: ^2.2.9
  intl: ^0.19.0
  logger: ^1.1.0
  fl_chart: ^0.35.0
  flutter_bloc: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: HSSaemaul
      fonts:
        - asset: assets/fonts/HSSaemaul-Regular.woff

  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/kakao_logo.png
    - assets/wisely-diary-logo.png
    - assets/emotions/sad.png
    - assets/emotions/anger.png
    - assets/emotions/embarrassed.png
    - assets/emotions/greatful.png
    - assets/emotions/injustice.png
    - assets/emotions/joy.png
    - assets/emotions/lovely.png
    - assets/emotions/proud.png
    - assets/emotions/relax.png
    - assets/emotions/worried.png
    - assets/audio/anger_bgm.mp3
    - assets/audio/embarrassed_bgm.mp3
    - assets/audio/greatful_bgm.mp3
    - assets/audio/injustice_bgm.mp3
    - assets/audio/joy_bgm.mp3
    - assets/audio/lovely_bgm.mp3
    - assets/audio/proud_bgm.mp3
    - assets/audio/relax_bgm.mp3
    - assets/audio/sad_bgm.mp3
    - assets/audio/worried_bgm.mp3
    - assets/cuttoon_icon.png
    - assets/letter_icon.png
    - assets/music_icon.png
    - assets/gift_icon.png
    - assets/diary_icon.png
    - assets/감사.png
    - assets/걱정.png
    - assets/당황.png
    - assets/뿌듯.png
    - assets/분노.png
    - assets/설렘.png
    - assets/슬픔.png
    - assets/신나.png
    - assets/억울.png
    - assets/편안.png
    - assets/text_image.png
    - assets/mic_img.png
    - assets/text_img.png
    - assets/stop_img.png
    - assets/File plus.png
    - .env
    - assets/cuttoon_icon.png
    - assets/gift_icon.png
    - assets/letter_icon.png
    - assets/music_icon.png